package com.bsmwireless.services.malfunction;

import android.content.Context;
import android.content.Intent;

import com.bsmwireless.common.App;
import com.bsmwireless.services.BaseMonitoringService;

/**
 * Service for monitoring diagnostic events which is generated by a black box
 */
public final class MalfunctionMonitoringService extends BaseMonitoringService {

    public static Intent createIntent(Context context) {
        return new Intent(context, MalfunctionMonitoringService.class);
    }

    @Override
    public void onCreate() {
        super.onCreate();
        App.getComponent().malfunctionServiceComponentBuilder()
                .build()
                .inject(this);

    }
}
