package com.bsmwireless.services.malfunction;

import android.app.Service;
import android.content.Context;
import android.content.Intent;
import android.os.IBinder;
import android.support.annotation.Nullable;

import com.bsmwireless.common.App;
import com.bsmwireless.models.BlackBoxModel;

import javax.inject.Inject;

import io.reactivex.Observable;

/**
 * Service for monitoring diagnostic events which is generated by a black box
 */
public class MalfunctionMonitoringService extends Service {

    @Inject
    MalfunctionServicePresenter presenter;

    public static Intent createIntent(Context context) {
        return new Intent(context, MalfunctionMonitoringService.class);
    }

    @Override
    public void onCreate() {
        super.onCreate();

        App.getComponent().malfunctionServiceComponentBuilder()
                .build()
                .inject(this);

        presenter.onCreate();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        presenter.onDestroy();
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }


}
